"""
Email delivery

Purpose : The only file that talks to the email service.
Spec    : Section 3.1
Look here when : An email order is not delivered.
"""

import logging

import httpx

from ..config import settings
from .whatsapp import ChannelUnavailable

log = logging.getLogger(__name__)

TIMEOUT_SECONDS = 15
API_URL = "https://api.resend.com/emails"


def is_configured() -> bool:
    return bool(settings.email_api_key)


def send(to_address: str, subject: str, body: str) -> str:
    """
    Plain text, deliberately. The message is generated by domain/message_builder
    and is meant to read like something a shop owner wrote; wrapping it in an
    HTML template would make a personal message look like marketing, which is
    exactly what a supplier ignores.

    Raises ChannelUnavailable so the caller queues rather than failing the order
    (spec 15.4). Shares the exception with whatsapp.py because the caller handles
    both channels identically.
    """
    if not is_configured():
        log.info("email not configured, would have sent %r to %s", subject, to_address)
        return "stub-email-id"

    try:
        response = httpx.post(
            API_URL,
            headers={"Authorization": f"Bearer {settings.email_api_key}"},
            json={
                "from": settings.email_from_address,
                "to": [to_address],
                "subject": subject,
                "text": body,
            },
            timeout=TIMEOUT_SECONDS,
        )
        response.raise_for_status()
        return response.json().get("id", "")
    except Exception as exc:
        log.warning("email send failed for %s: %s", to_address, exc)
        raise ChannelUnavailable(str(exc)) from exc
