/**
 * Ordering API
 * 
 * Purpose : Calls the restock popup endpoints: generate, validate, send.
 * Spec    : Section 6.5
 * Look here when : The popup cannot load or send.
 */

import { mock, request, useMockData } from './client';
import type { RestockDraft, RestockLine, SupplierView } from '../types/api';
import type { Channel } from '../types/database';

/**
 * Spec 6.5 — the message body is generated by the backend, never assembled in the app, so
 * the wording can be improved without shipping a new version. This local version exists only
 * while the backend does not, and is replaced by the request below.
 */
export async function generateMessage(
  lines: RestockLine[],
  supplier: SupplierView | null,
  shopName = 'Wasantha Kade',
): Promise<string> {
  if (useMockData) {
    const to = supplier?.business_name ?? 'your supplier';
    const items = lines
      .map((l) => '- ' + l.name + ' ' + l.pack_size + ', requested ' + l.quantity_requested + ' units')
      .join('\n');
    const body = [
      'Hi ' + to + ',',
      '',
      'This is a reorder from ' + shopName + '. The following items have fallen below our minimum threshold and require restocking:',
      '',
      items,
      '',
      'Please confirm receipt of this order and let us know if any items are currently out of stock.',
      '',
      'Thank you!',
    ].join('\n');
    return mock(body, 120);
  }
  return request('/customer/ordering/message', {
    method: 'POST',
    body: JSON.stringify({
      supplier_id: supplier?.id,
      lines: lines.map((l) => ({ stock_item_id: l.stock_item_id, quantity: l.quantity_requested })),
    }),
  });
}

/**
 * Spec 6.5 and 15.4 — sending must be idempotent, so a repeated submission on a poor
 * connection creates one order and not two. The key is generated per popup session and
 * replayed on retry; the backend uses core/idempotency.py to recognise it.
 */
export async function sendOrder(
  draft: RestockDraft,
  channel: Channel,
  idempotencyKey: string,
): Promise<{ order_id: string }> {
  if (useMockData) return mock({ order_id: 'o-new' }, 400);
  return request('/customer/ordering/send', {
    method: 'POST',
    headers: { 'Idempotency-Key': idempotencyKey },
    body: JSON.stringify({
      supplier_id: draft.supplier?.id,
      channel,
      message_body: draft.message_body,
      message_edited: draft.message_edited,
      requested_delivery_date: draft.requested_delivery_date,
      notes: draft.notes,
      lines: draft.lines.map((l) => ({
        stock_item_id: l.stock_item_id,
        quantity: l.quantity_requested,
      })),
    }),
  });
}

/** A key per popup session. Crypto is not needed; this only has to be unique per attempt. */
export function newIdempotencyKey(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 10);
}
