/**
 * Ordering API
 * 
 * Purpose : Calls the restock popup endpoints: generate, validate, send.
 * Spec    : Section 6.5
 * Look here when : The popup cannot load or send.
 */

import { mock, request, useMockData } from './client';
import type { RestockDraft, RestockLine, SupplierView } from '../types/api';
import type { Channel } from '../types/database';

/**
 * Spec 6.5 — the message body is generated by the backend, never assembled in the app, so
 * the wording can be improved without shipping a new version. This local version exists only
 * while the backend does not, and is replaced by the request below.
 */
export async function generateMessage(
  lines: RestockLine[],
  supplier: SupplierView | null,
  shopName = 'Wasantha Kade',
  /** Folded into the text by the backend, so the preview is what the supplier will read. */
  extras: { notes?: string; requested_delivery_date?: string | null } = {},
): Promise<{ message_body: string; warnings: string[]; duplicates: string[] }> {
  if (useMockData) {
    const to = supplier?.business_name ?? 'your supplier';
    const items = lines
      .map((l) => '- ' + l.name + ' ' + l.pack_size + ', requested ' + l.quantity_requested + ' units')
      .join('\n');
    const body = [
      'Hi ' + to + ',',
      '',
      'This is a reorder from ' + shopName + '. The following items have fallen below our minimum threshold and require restocking:',
      '',
      items,
      '',
      'Please confirm receipt of this order and let us know if any items are currently out of stock.',
      '',
      'Thank you!',
    ].join('\n');
    return mock({ message_body: body, warnings: [], duplicates: [] }, 120);
  }
  /**
   * `problems` are the lines the backend would refuse; the popup does its own per-line
   * check for those. `warnings` are the ones it will accept but the owner should see --
   * today, a product already on order with a different supplier (spec 6.5).
   */
  const result = await request<{
    message_body: string;
    problems: string[];
    warnings: string[];
    duplicates: string[];
  }>(
    '/customer/ordering/message',
    {
      method: 'POST',
      body: JSON.stringify({
        supplier_id: supplier?.id,
        lines: lines.map((l) => ({ stock_item_id: l.stock_item_id, quantity: l.quantity_requested })),
        notes: extras.notes || null,
        // An emptied date box holds '', which is not a date. Send nothing instead of ''.
        requested_delivery_date: extras.requested_delivery_date || null,
      }),
    },
  );
  return {
    message_body: result.message_body,
    warnings: result.warnings ?? [],
    /** Refused unless confirmed: the same product already on order with this supplier. */
    duplicates: result.duplicates ?? [],
  };
}

/**
 * Spec 6.5 and 15.4 — sending must be idempotent, so a repeated submission on a poor
 * connection creates one order and not two. The key is generated per popup session and
 * replayed on retry; the backend uses core/idempotency.py to recognise it.
 */
export async function sendOrder(
  draft: RestockDraft,
  channel: Channel,
  idempotencyKey: string,
): Promise<{ order_id: string }> {
  if (useMockData) return mock({ order_id: 'o-new' }, 400);
  return request('/customer/ordering/send', {
    method: 'POST',
    headers: { 'Idempotency-Key': idempotencyKey },
    body: JSON.stringify({
      supplier_id: draft.supplier?.id,
      channel,
      message_body: draft.message_body,
      message_edited: draft.message_edited,
      // The backend refuses a repeat order with the same supplier unless this says the
      // owner was shown it and agreed.
      allow_duplicate: draft.allow_duplicate,
      // An emptied date box holds '', which is not a date. Send nothing instead of ''.
      requested_delivery_date: draft.requested_delivery_date || null,
      notes: draft.notes,
      lines: draft.lines.map((l) => ({
        stock_item_id: l.stock_item_id,
        quantity: l.quantity_requested,
      })),
    }),
  });
}

/** A key per popup session. Crypto is not needed; this only has to be unique per attempt. */
export function newIdempotencyKey(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 10);
}
