"""
Restock message generation

Purpose : Builds the restock message text from shop name, products, quantities, delivery date and notes. Server-side so wording can change without an app release.
Spec    : Section 6.5
Look here when : The generated message has wrong wording, a missing product, or a wrong total.
"""

from dataclasses import dataclass
from datetime import date


@dataclass(frozen=True)
class MessageLine:
    name: str
    pack_size: str
    quantity_requested: int
    current_quantity: int | None = None
    unit_price: float | None = None


def _format_date(value: date | str | None) -> str | None:
    if value is None:
        return None
    if isinstance(value, str):
        try:
            value = date.fromisoformat(value)
        except ValueError:
            return value
    return value.strftime("%d %B %Y")


def build(
    *,
    shop_name: str,
    supplier_name: str,
    lines: list[MessageLine],
    delivery_address: str | None = None,
    requested_delivery_date: date | str | None = None,
    notes: str | None = None,
) -> str:
    """
    Spec 6.5: generated by the backend, never assembled in the app, so the wording
    can be improved without shipping a new version and two implementations cannot
    drift apart.

    After changing anything here, run backend/tests/test_message_builder.py --
    that file exists to be the check on this one.
    """
    parts: list[str] = [f"Hi {supplier_name},", ""]

    if len(lines) == 1:
        parts.append(
            f"This is a reorder from {shop_name}. The following item has fallen below "
            "our minimum threshold and requires restocking:"
        )
    else:
        parts.append(
            f"This is a reorder from {shop_name}. The following items have fallen below "
            "our minimum threshold and require restocking:"
        )
    parts.append("")

    for line in lines:
        parts.append(f"- {line.name} {line.pack_size}")
        if line.current_quantity is not None:
            parts.append(f"  Current stock: {line.current_quantity} units")
        parts.append(f"  Requested quantity: {line.quantity_requested} units")
    parts.append("")

    total = sum(
        line.quantity_requested * line.unit_price
        for line in lines
        if line.unit_price is not None
    )
    if total > 0:
        parts.append(f"Estimated total: LKR {total:,.2f}")
        parts.append("")

    if delivery_address:
        parts.append(f"Delivery address: {delivery_address}")
    formatted = _format_date(requested_delivery_date)
    if formatted:
        parts.append(f"Preferred delivery: by {formatted}")
    if delivery_address or formatted:
        parts.append("")

    if notes and notes.strip():
        parts.append(notes.strip())
        parts.append("")

    parts.append(
        "Please confirm receipt of this order and let us know if any items are "
        "currently out of stock."
    )
    parts.append("")
    parts.append("Thank you!")
    parts.append(shop_name)

    return "\n".join(parts)


def was_edited(current: str, generated: str) -> bool:
    """
    Spec 6.5 drives the overwrite warning off this comparison rather than a flag
    set on every keystroke. A customer who edits the message and then types the
    original back has lost nothing, so they should not be warned.
    """
    return current.strip() != generated.strip()
